version: "3.1"
networks:
  cl:
    external: true
services:
  cmak:
    container_name: cmak
    networks:
      - cl
    image: vimagick/cmak:latest 
    restart: always
    environment:
      - JVM_OPT='-Xmx512m'
    command:
      - "-Dcmak.zkhosts=zookeeper:2181"
      - "-DbasicAuthentication.enabled=true"
      - "-DbasicAuthentication.username=username"
      - "-DbasicAuthentication.password=password"
    ports:
      - "9000:9000"
