version: '2'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181  
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-tier
  kafka:
    container_name: broker
    ports:
      - "9092:9092"
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
