version: '3'
networks:
  cl:
    external: true
services:
  # eagle:
  #   container_name: efak
  #   image: nickzurich/efak:3.0.1
  #   environment: 
  #     KE_JAVA_OPTS: -Xms512M -Xmx512M
  #     EFAK_CLUSTER_ZK_LIST: zookeeper:2181/kafka_test
  #   networks:
  #     - cl
  #   ports:
  #     - 8048:8048
  broker:
    networks: 
      - cl
    image: wurstmeister/kafka:2.13-2.8.1 
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181/kafka_test'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OFFICEHOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.25.134.200:9092
      KAFKA_ADVERTISED_HOST_NAME: 10.25.134.200
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: -Xmx512m
