version: '2'
networks:
  cl:
    external: true

services:
  kafka:
    restart: always
    container_name: kafka
    image: bitnami/kafka:latest 
    ports:
      - "9093:9092"
    volumes:
      - "./data/kafka:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181/kafka_bitnami
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.26.183.39:9093
    networks:
      - cl
