version: '2'
networks:
  cl:
    external: true
services:
  cmak:
    networks:
      - cl
    image: ghcr.io/eshepelyuk/dckr/cmak-3.0.0.5:latest
    restart: always
    command:
      - "-Dcmak.zkhosts=zookeeper:2181"
      - "-DbasicAuthentication.enabled=true"
      - "-DbasicAuthentication.username=username"
      - "-DbasicAuthentication.password=password"
    ports:
      - "9000:9000"
  zookeeper:
    networks:
      - cl
    container_name: zookeeper
    image: zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    networks:
      - cl
    container_name: kafka
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: 10.25.134.200
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.25.134.200:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./data/kafka/var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
