version: '3'
networks:
  cl:
    external: true
services:
    redis:
        networks:
            - cl
        image: redis:7
        restart: always
        container_name: redis
        ports:
            - '6379:6379'
