version: '3'
networks:
  cl:
    external: true
services:
  zookeeper_2191:
    networks:
      - cl
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper_2191
    ports:
      - "2191:2191"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2191
      ZOOKEEPER_TICK_TIME: 2000
