version: '3'
networks:
  cl:
    external: true
services:
  zookeeper:
    ports:
      - 2181:2181
    networks: 
      - cl
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000