version: '3'
networks:
  cl:
    external: true
services:
  zookeeper:
    restart: always 
    networks:
      - cl
    image: zookeeper:3.8.1
    container_name: zookeeper
    ports:
      - "2182:2181"
    environment:
      JVMFLAGS: "-Xmx1024m"
