version: '3.1'
networks:
    cl:
        external: true
services:
  ql:
    container_name: qinglong
    image: whyour/qinglong:latest
    volumes:
      - ./data:/ql/data
    ports:
      - "5700:5700"
    restart: always
    networks:
        - cl
